name: Release
on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install UV
        run: pip install uv

      - name: Create uv virtual environment
        run: uv venv

      - name: Install build tools
        run: uv pip install build twine

      - name: Build distributions
        run: uv run python -m build --wheel --sdist

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: uv run python -m twine upload dist/*
